// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: ping/v1/ping.proto

package pingv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_ping_v1_ping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ping_v1_ping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_ping_v1_ping_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the pong
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_ping_v1_ping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ping_v1_ping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_ping_v1_ping_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ping_v1_ping_proto protoreflect.FileDescriptor

const file_ping_v1_ping_proto_rawDesc = "" +
	"\n" +
	"\x12ping/v1/ping.proto\x12\aping.v1\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2D\n" +
	"\vPingService\x125\n" +
	"\x04Ping\x12\x14.ping.v1.PingRequest\x1a\x15.ping.v1.PingResponse\"\x00B\x96\x01\n" +
	"\vcom.ping.v1B\tPingProtoP\x01Z?github.com/pitabwire/frame/frametests/rpcservice/ping/v1;pingv1\xa2\x02\x03PXX\xaa\x02\aPing.V1\xca\x02\aPing\\V1\xe2\x02\x13Ping\\V1\\GPBMetadata\xea\x02\bPing::V1b\x06proto3"

var (
	file_ping_v1_ping_proto_rawDescOnce sync.Once
	file_ping_v1_ping_proto_rawDescData []byte
)

func file_ping_v1_ping_proto_rawDescGZIP() []byte {
	file_ping_v1_ping_proto_rawDescOnce.Do(func() {
		file_ping_v1_ping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ping_v1_ping_proto_rawDesc), len(file_ping_v1_ping_proto_rawDesc)))
	})
	return file_ping_v1_ping_proto_rawDescData
}

var file_ping_v1_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ping_v1_ping_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: ping.v1.PingRequest
	(*PingResponse)(nil), // 1: ping.v1.PingResponse
}
var file_ping_v1_ping_proto_depIdxs = []int32{
	0, // 0: ping.v1.PingService.Ping:input_type -> ping.v1.PingRequest
	1, // 1: ping.v1.PingService.Ping:output_type -> ping.v1.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ping_v1_ping_proto_init() }
func file_ping_v1_ping_proto_init() {
	if File_ping_v1_ping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ping_v1_ping_proto_rawDesc), len(file_ping_v1_ping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ping_v1_ping_proto_goTypes,
		DependencyIndexes: file_ping_v1_ping_proto_depIdxs,
		MessageInfos:      file_ping_v1_ping_proto_msgTypes,
	}.Build()
	File_ping_v1_ping_proto = out.File
	file_ping_v1_ping_proto_goTypes = nil
	file_ping_v1_ping_proto_depIdxs = nil
}
