name: "Bug report"
description: "Report a bug in Frame"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide minimal steps.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Traces
      render: shell
  - type: input
    id: version
    attributes:
      label: Frame Version / Commit
      placeholder: e.g. v0.9.1 or commit SHA
    validations:
      required: true
  - type: input
    id: go
    attributes:
      label: Go Version
      placeholder: e.g. go1.22.2
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. Ubuntu 22.04
    validations:
      required: true
